# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pictureUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(30, 20, 271, 391))
        self.photo.setText("")

        self.photo.setPixmap(QtGui.QPixmap("0012.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setGeometry(QtCore.QRect(30, 420, 93, 28))
        self.previous.setObjectName("previous")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(200, 420, 93, 28))
        self.next.setObjectName("next")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))

        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.previous.clicked.connect(self.show_previous)
        self.next.clicked.connect(self.show_next)
        # popup
        self.next.clicked.connect(self.show_popup)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.previous.setText(_translate("MainWindow", "Previous"))
        self.next.setText(_translate("MainWindow", "Next"))

    def show_previous(self):
        self.photo.setPixmap(QtGui.QPixmap("C:\\Users\\user\\Desktop\\UI_practice_folder\\0012.jpg"))

    def show_next(self):
        self.photo.setPixmap(QtGui.QPixmap("C:\\Users\\user\\Desktop\\UI_practice_folder\\0014.jpg"))
    
    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Tips")
        msg.setText("Please place the images based on the below structure")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel|QMessageBox.Retry|QMessageBox.Ignore)
        msg.setDefaultButton(QMessageBox.Ok)

        msg.setInformativeText("Informative Text")
        msg.setDetailedText("|-Root-Folder" + "\n" +
                                "|  |-instant-ngp.exe" + "\n" +
                                "|  |-Scripts" + "\n" +
                                "|  |  |-nerf-automation.py" + "\n" +
                                "|  |  |-colmap2nerf.py" + "\n" +
                                "|  |  |-..." + "\n" +
                                "|  |"  + "\n" +
                                "|  |-data" + "\n" +
                                "|    |-nerf" + "\n" +
                                "|     |-transformed.json" + "\n" +
                                "|     |-Images" + "\n" +
                                "|       |-0001.jpg" + "\n" +
                                "|       |-0002.jpg" + "\n" +
                                "|       |-0003.jpg" + "\n" +
                                "|       |-...")
        msg.buttonClicked.connect(self.popup_button)
        x = msg.exec_()
    
    def popup_button(self, i):
        print(i.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
